### ISSUE TITLE
improving verifybamid2 resource consumption

### ISSUE THREAD

**Issue by nicolas-bertin** [c-BIG/NPM-sample-qc#107]
https://github.com/c-BIG/NPM-sample-qc/blob/fa9d23ff508011987c86b623f05882aa7d428ae8/modules/verifybamid2/main.nf#L24C5-L24C17

1.  ... need to add `--NumThread ${task.cpus} ` (see https://github.com/Griffan/VerifyBamID#usage)
2.  given the nf report cpu usage : it might be good investigating  `--NumThread ${2 * task.cpus}`

**Comment by justinjj24** [comment]
>         withName: 'verifybamid2' {
> 
>         // errorStrategy 'ignore'
>         errorStrategy { task.exitStatus in [1,104,134,137,138,139,140,143,247] ? 'retry' : 'ignore' }
> 
>         cpus = 4
>         disk = '50 GB'
>         memory = { 1.GB * task.attempt }
> 
>         publishDir = [
>             path: "${params.publishdir}/verifybamid2",
>             mode: params.publish_mode,
>         ]
>     }

    
    `vf_threads = (int) Math.ceil(task.cpus*2)`
    `--NumThread ${vf_threads}`
