### ISSUE TITLE
Pipeline reproducibility

### ISSUE THREAD

**Issue by skanwal** [c-BIG/NPM-sample-qc#11]
Hello, 

As discussed in the last GHIF-QC meeting, UMCCR has attempted to run `NPM-sample-qc` pipeline on Amazon Genomics CLI (AGC) which makes it simple for software developers and researchers to easily and quickly provision, configure, and scale cloud resources to run genomic workflows.

We would like to use this issue as a basis for discussion in our upcoming meeting.

1. `nextflow.config` exists inside `conf` directory. Nextflow executor expects in to be present in the base directory, which is also a best practice for nextflow pipelines as noted in nf-core pipeline, for example https://github.com/nf-core/rnaseq.

**Proposed solution:**

Move nextfow config to the base directory.

2. It's a requirement to use `cram` as an input ID in  `input.yaml`, even if the input is a bam file. This isn't very intuitive, IMO. 

**Proposed solution:**

This would benefit form updating pipeline help for clarification.

3. The way `params.container`  is [set](https://github.com/c-BIG/NPM-sample-qc/blob/master/conf/nextflow.config#L4) is seen by Nextflow as an ordinary variable. 

**Proposed solution:**

Add an entry to the `process` block in the `nextflow.config` as:

```
process.container = 'justinjj24/npm-sample-qc:latest'
```

4. I received an error while executing `picard_collect_wgs_metrics`process.

```
Caused by:
 Cannot invoke method toGiga() on null object
 
Source block:
 “”"
     java -Dsamjdk.compression_level=2 -Xmx${task.memory.toGiga()}G -Xms4000m \
         -XX:ConcGCThreads=${task.cpus} -XX:+UseConcMarkSweepGC \
         -XX:ParallelGCThreads=${task.cpus} \
         -jar /usr/local/conda/envs/npm-sample-qc/share/picard-2.21.7-0/picard.jar \
         CollectWgsMetrics \
         R=${ref_fa} \
         I=${params.sample_id}.bam \
         O=${params.sample_id}.wgs_metrics.txt
     “”"
```

**Proposed solution:**

Reading online on NF best practices, I would suggest loading base config by default for all pipelines in `nextflow.config` as the defined parameters are being references in the process definition. 

```
includeConfig 'conf/base.config'
```

5. Process `picard_collect_wgs_metrics` is erroring out with:

```
Error: Unable to access jarfile /usr/local/conda/envs/npm-sample-qc/share/picard-2.21.7-0/picard.jar | Error: Unable to access jarfile /usr/local/conda/envs/npm-sample-qc/share/picard-2.21.7-0/picard.jar
```

The pipeline is using the jar file at the following [line](https://github.com/c-BIG/NPM-sample-qc/blob/master/main.nf#L329), which assumes the pipeline will be executed using conda or singularity and in this case we are running the pipeline using docker container.

**Proposed solution:**

This issue can be resolved by making jar file configurable via variable within a config file. So the user has control over the execution environment for the pipeline.

6. Process `verifybamid2` is erroring out with:

```
Open file:s3://umccr-research-dev/npm-qc-pipeline/1000g.phase3.100k.b38.vcf.gz.dat.bed	 failed, exit! | Open file:s3://umccr-research-dev/npm-qc-pipeline/1000g.phase3.100k.b38.vcf.gz.dat.bed failed, exit!
```

It seems the pipeline definition is hardcoding files in [input block](https://github.com/c-BIG/NPM-sample-qc/blob/8f6883c96717e566a1db28170d284190837f0f90/main.nf#L462) of the step by directly calling `params.`.

**Proposed solution:**

The input reference data should be first staged by specifying these in `[input](https://github.com/c-BIG/NPM-sample-qc/blob/8f6883c96717e566a1db28170d284190837f0f90/main.nf#L453)` block of the process explicitly so that there are made available at runtime.

7. Process `sg10k_cov_062017` is erroring out with following error:

```
Caused by:
  Process `sg10k_cov_062017 (1)` terminated with an error exit status (127)

Command executed:

  sg10k-cov-062017.sh NA12878.bam > NA12878.sg10k_cov_062017.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: sg10k-cov-062017.sh: command not found
```

**Proposed solution:**

The binary for this step is copied in [singularity.def](https://github.com/c-BIG/NPM-sample-qc/blob/8f6883c96717e566a1db28170d284190837f0f90/containers/singularity.def#L43) file from https://github.com/c-BIG/sg10k-cov.git, which is probably private, hence inaccessible for the users. 

Also unsure, if `singularity.def` is the right place to define this step. If so, this will also need to be shipped with the offical container for this pipeline.

8. This is rather a question/comment. We noted that the pipeline is written using `DSL1`. Nextflow DSL2 has been introduced nearly [2 years ago](https://www.nextflow.io/blog/2020/dsl2-is-here.html) and established pipeline collections such as those in [nf-core](https://nf-co.re/pipelines) have migrated their pipelines to DSL2 syntax. Are there any plans to update this pipeline as well? Any particular reasons for using DSL1?

cc-ing @scwatts in this issue, who is our go to NF expert and helped me understand NF specific technicalities.

**Comment by nicolas-bertin** [comment]
Hi Sehrish,
Thanks for the very thorough feedback. 
Let us (@justinjj24 @rodrigotoro and @nicolas-bertin) digest it.
Some of the points you raised already are on our radar : "interface" cleanup (i.e bam/cram),  dropping the deprecated/irrlevant to the GHIF/GA4GH effort sg10k-cov metric and associated codebase, .. amongst the few points you raised)

**Comment by justinjj24** [comment]
Hi Sehrish,

Thank you for raising number of issues in detail. Appreciate if you could create an individual issue. It'll be much better for us address the issue and close. Thanks

**Comment by skanwal** [comment]
Hi @justinjj24 

I have opened up a series of issues, as linked above.

**Comment by nicolas-bertin** [comment]
Thanks @skanwal . Let's close this issue and tackle each individual "Pipeline Repro" issue you raised
