### ISSUE TITLE
dockerfile should assume the git repo master branch is to be used

### ISSUE THREAD

**Issue by nicolas-bertin** [c-BIG/NPM-sample-qc#12]
https://github.com/c-BIG/NPM-sample-qc/blob/1c342439ee8258389201d802d4b9b6feda702160/containers/Dockerfile#L47

**Comment by justinjj24** [comment]
Will implement the changes in the next release, which included the MultiQC_NPM repo migrated into the NPM-sample-qc

**Comment by nicolas-bertin** [comment]
solved in https://github.com/c-BIG/NPM-sample-qc/commit/11d6a9a4e22f43f75c87555b2f6c56c99c827699
