### ISSUE TITLE
Move nextfow config to the base directory

### ISSUE THREAD

**Issue by skanwal** [c-BIG/NPM-sample-qc#18]
From https://github.com/c-BIG/NPM-sample-qc/issues/11#issuecomment-1189881615

nextflow.config exists inside conf directory. Nextflow executor expects in to be present in the base directory, which is also a best practice for nextflow pipelines as noted in nf-core pipeline, for example https://github.com/nf-core/rnaseq.

**Proposed solution:**

Move nextfow config to the base directory.

**Comment by justinjj24** [comment]
Agree. work in progress...

**Comment by justinjj24** [comment]
reorganised in the branch `release-1.1-dev`
