### ISSUE TITLE
Impose the use of `memory` in process conf if/when needed in the process src

### ISSUE THREAD

**Issue by skanwal** [c-BIG/NPM-sample-qc#21]
From https://github.com/c-BIG/NPM-sample-qc/issues/11

 I received an error while executing `picard_collect_wgs_metrics`process.

```
Caused by:
 Cannot invoke method toGiga() on null object
 
Source block:
 “”"
     java -Dsamjdk.compression_level=2 -Xmx${task.memory.toGiga()}G -Xms4000m \
         -XX:ConcGCThreads=${task.cpus} -XX:+UseConcMarkSweepGC \
         -XX:ParallelGCThreads=${task.cpus} \
         -jar /usr/local/conda/envs/npm-sample-qc/share/picard-2.21.7-0/picard.jar \
         CollectWgsMetrics \
         R=${ref_fa} \
         I=${params.sample_id}.bam \
         O=${params.sample_id}.wgs_metrics.txt
     “”"
```

**Proposed solution:**

Reading online on NF best practices, I would suggest loading base config by default for all pipelines in `nextflow.config` as the defined parameters are being references in the process definition. 

```
includeConfig 'conf/base.config'
```

**Comment by justinjj24** [comment]
I agree. Will be implemented in the current development branch.

**Comment by nicolas-bertin** [comment]
solved in https://github.com/c-BIG/NPM-sample-qc/tree/v0.4
