### ISSUE TITLE
Making public resource files easily available

### ISSUE THREAD

**Issue by skanwal** [c-BIG/NPM-sample-qc#23]
From https://github.com/c-BIG/NPM-sample-qc/issues/11

Process `verifybamid2` is erroring out with:

```
Open file:s3://umccr-research-dev/npm-qc-pipeline/1000g.phase3.100k.b38.vcf.gz.dat.bed	 failed, exit! | Open file:s3://umccr-research-dev/npm-qc-pipeline/1000g.phase3.100k.b38.vcf.gz.dat.bed failed, exit!
```

It seems the pipeline definition is hardcoding files in [input block](https://github.com/c-BIG/NPM-sample-qc/blob/8f6883c96717e566a1db28170d284190837f0f90/main.nf#L462) of the step by directly calling `params.`.

**Proposed solution:**

The input reference data should be first staged by specifying these in `[input](https://github.com/c-BIG/NPM-sample-qc/blob/8f6883c96717e566a1db28170d284190837f0f90/main.nf#L453)` block of the process explicitly so that there are made available at runtime.

**Comment by justinjj24** [comment]
To run the workflow locally the data for the `verifybamid2` should be kept in local disk. For awsbatch keep it in your s3 bucket to stage. Again please try `awsbatch-1kg-100sample` or `awsbatch-dev` soon it will be merged to master branch.

**Comment by nicolas-bertin** [comment]
@skanwal and @justinjj24 it actually begs for some public resource files to be made easily publicly available (i.e akin aws opendata registry or some other "legacy" datasource)... let's talk about the best way to go about it during our next conf call

**Comment by justinjj24** [comment]
renamed the issue title for ease of referencing

**Comment by nicolas-bertin** [comment]
solved in https://github.com/c-BIG/NPM-sample-qc/commit/03827ba68ca9f9179d7d94aa8dc184864a9b1c6e and  #35
