### ISSUE TITLE
aligning nexflow.config with dockstore requirements/expectations 

### ISSUE THREAD

**Issue by nicolas-bertin** [c-BIG/NPM-sample-qc#54]
Execution of the workflow via dockstore will require couple modifications to nexflow.config file, such that the workflow can be executed without any explicit mention of a `-profile`. e.g. : 

- current `conf/base.config` (as well as eventually other cnof/xxx.config files) need to be called (`includeConfig 'conf/base.config'`) outside of any given profile in `nexflow.config`

**Comment by justinjj24** [comment]
Implemented in branch [feature/dsl2-v3](https://github.com/c-BIG/NPM-sample-qc/blob/feature/dsl2-v3/nextflow.config) to execute the workflow without calling `-profile`

```
process.container = 'cbig/npm-sample-qc:v0.51'
docker.enabled = true
docker.runOptions = '-u \$(id -u):\$(id -g)'
```
