### ISSUE TITLE
Verify datamash function madraw fulfil the description in the GHIF_WGS_QC word doc

### ISSUE THREAD

**Issue by justinjj24** [c-BIG/NPM-sample-qc#70]
https://github.com/c-BIG/NPM-sample-qc/blob/491159b853f31cfe7bed486076c128aab42a0926/main.nf#L172

Ensure the process `mad_autosome_coverage` metric calculation derived using `datamash` `mdraw` match with the description in the GHIF_WGS_QC document.

```
Example metric: Genome coverage uniformity
Id: autosome_coverage_uniformity
Description: The percentage of bases with more or less than 25% coverage difference from the mean autosome coverage
Source: in-house tool based on mosdepth v0.3.2 calculating (PCT < 0.75 * mean_autosome_coverage) + (PCT > 1.25 * mean_autosome_coverage) 
Implementation details: same as mean_autosome_coverage.
```

**Comment by mhebrard** [comment]
`mad_autosome_coverage` metric computed by `npm-sample-qc` follow the description in the documentation stated as 

> The median absolute deviation of coverage in autosomes, after coverage filters are applied (see mean_autosome_coverage for details).

GHIF_WGS_QC documentation needs to be updated accordingly
