### ISSUE TITLE
Use samtools stats instead of picard CollectInsertSizeMetrics

### ISSUE THREAD

**Issue by justinjj24** [c-BIG/NPM-sample-qc#77]
https://github.com/c-BIG/NPM-sample-qc/blob/1ea47eb7d9df3b6363c67cc9fa008e7c7a99e0de/bin/metrics/metrics.py#L124

- Use `samtools stats` instead of `picard` `CollectInsertSizeMetrics` to exclude `secondary` and supplementary reads? with or without remove duplicate option!
- unsure about the impact of sec/suppl reads for the `mean insert size` calculation and whether it included in the `picard CollectInsertSizeMetrics`

https://gatk.broadinstitute.org/hc/en-us/articles/360037055772-CollectInsertSizeMetrics-Picard-

**Comment by mhebrard** [comment]
after investigation of picard documentation: 
> The CollectInsertSizeMetrics tool outputs the percentages of read pairs in each of the three orientations (FR, RF, and TANDEM) as a histogram. In addition, the insert size distribution is output as both a histogram (.insert_size_Histogram.pdf) and as a data table (.insert_size_metrics.txt).

> The mean insert size of the "core" of the distribution. Artefactual outliers in the distribution often cause calculation of nonsensical mean and stdev values. To avoid this the distribution is first trimmed to a "core" distribution of +/- N median absolute deviations around the median insert size. By default N=10, but this is configurable.

after investigation on samtools

> insert size average - the average absolute template length for paired and mapped reads.
insert size standard deviation - standard deviation for the average template length distribution.
inward oriented pairs - number of paired reads with flag 0x40 (64) set and flag 0x10 (16) not set or with flag 0x80 (128) set and flag 0x10 (16) set.
outward oriented pairs - number of paired reads with flag 0x40 (64) set and flag 0x10 (16) set or with flag 0x80 (128) set and flag 0x10 (16) not set.
pairs with other orientation - number of paired reads that don't fall in any of the above two categories.

It seems that neither of the two popular tool are filtering "properly paired reads" ...
Therefore we should suggest to relax the metric definition to not enforce properly paired reads
