### ISSUE TITLE
ga4gh/quality-control-wgs metrics_definitions.md - Percent reads mapped

### ISSUE THREAD

**Issue by justinjj24** [c-BIG/NPM-sample-qc#84]
>Description: The percentage of short paired-end sequencing [high quality](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#high-quality-reads), [non duplicated](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#duplicated-reads) reads, [primary alignments](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#primary-alignments), achieving a [mapping quality](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#mapping-quality) of 0 or greater on [GRCh38 assembly](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#grch38-assembly). It is critcal that the (BAM/CRAM) alignment files be readily marked for [duplicated reads](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#duplicated-reads).

>Implementation details: In the NPM-sample-QC reference implementation it is computed using [samtools stats](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#samtools-stats), reporting the percentage of reads mapped on GRCh38 assembly with MAPQ > 0. Duplicated reads are incuded.

**incuded -> included**

1) Hence, the duplicated reads are included in the implementation does it necessary to mention the following comment in the description or change the code to remove duplicate reads? 
  - **It is critcal that the (BAM/CRAM) alignment files be readily marked for [duplicated reads](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#duplicated-reads).**
  
    Based on our internal discussion https://sg-npm.atlassian.net/jira/software/projects/SQC/boards/12?selectedIssue=SQC-61
  >let's keep duplicate reads.
  >rationale  : the goal of this metric should be to get a sesne of how much of your library map to human vs bacteria, virus, >(some contaminating non-human dna), …   so if all your reads are duplicated but all map to grch38 the % shoud be 100, not >50%
  

2) Good to include the comment given below or remove the `high quality` from the description? The `high quality` reads also not part of the description in the proposed GHIF WGS QC document!

   - NPM-sample-qc implementation metric `Percent reads mapped` doesn't select [high quality](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#high-quality-reads) reads using `samtools stats`.
   - **It is critcal that the (BAM/CRAM) alignment files generated only from the illumina PF reads.**

**Comment by justinjj24** [comment]
state No minimum mapping-quality is imposed or No filter on mapping qualiy is applied, instead of MAPQ > 0 are considered?

A mapping quality of zero in [bwa](http://bio-bwa.sourceforge.net/) means that the read maps to multiple locations with the same quality and that the mapper has picked one of these positions at random.

This process includes duplicate reads.

**Comment by mhebrard** [comment]
to fix the imlementation details "with MAPQ > 0" is wrong - there is no MAPQ filter in the implementation

**Comment by mhebrard** [comment]
Rephrase deffinition to clarify MQ criteria as 

> - **Description:** The percentage of short paired-end sequencing [high quality](#high-quality-reads), [non duplicated](#duplicated-reads) reads, [primary alignments](#primary-alignments), mapped on [GRCh38 assembly](#grch38-assembly). No minimum [mapping quality](#mapping-quality) is imposed. It is critical that the (BAM/CRAM) alignment files be readily marked for [duplicated reads](#duplicated-reads).
> - **Implementation details:** In the NPM-sample-QC reference implementation it is computed using [samtools stats](#samtools-stats), reporting the percentage of reads mapped on GRCh38 assembly. Duplicated reads are included. No mapping qualiy is applied.

**Comment by mhebrard** [comment]
Rephrase to include duplicated reads as agreed previously

> let's keep duplicate reads.
rationale: the goal of this metric should be to get a sense of how much of your library map to human

> - **Description:** The percentage of short paired-end sequencing [high quality reads](#high-quality-reads), [primary alignments](#primary-alignments), mapped on [GRCh38 assembly](#grch38-assembly). [Duplicated reads](#duplicated-reads) are included. No minimum [mapping quality](#mapping-quality) is imposed.
