### ISSUE TITLE
ga4gh/quality-control-wgs metrics_definitions.md - Mean insert size

### ISSUE THREAD

**Issue by justinjj24** [c-BIG/NPM-sample-qc#86]
>Description: The mean insert size of short paired-end sequencing [high quality](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#high-quality-reads), [non duplicated](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#duplicated-reads), properly paired reads, [primary alignments](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#primary-alignments), achieving a [mapping quality](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#mapping-quality) of 0 or greater on [GRCh38 assembly](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#grch38-assembly).

>Implementation details: In the NPM-sample-QC reference implementation it is computed using [GATK Picard’s CollectInsertSizeMetrics](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#picard-collectinsertsizemetrics), reporting the MEAN_INSERT_SIZE field. Only the non duplicated, properly paired reads mapped on GRCh38 assembly with MAPQ > 0 are considered.

Good to include the comment given below or remove the `high quality` from the description? The `high quality` reads also not part of the description in the proposed GHIF WGS QC document!

   - NPM-sample-qc implementation metric `Mean insert size` doesn't select [high quality](https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md#high-quality-reads) reads using `picard-collectinsertsizemetrics`.
   - **It is critcal that the (BAM/CRAM) alignment files generated only from the illumina PF reads.**

**Comment by justinjj24** [comment]
state No minimum mapping-quality is imposed or No filter on mapping qualiy is applied, instead of MAPQ > 0 are considered?

A mapping quality of zero in [bwa](http://bio-bwa.sourceforge.net/) means that the read maps to multiple locations with the same quality and that the mapper has picked one of these positions at random. 

This process uses non duplicate reads only.

**Comment by mhebrard** [comment]
Fix typo, clarify MQ criteria & exclude duplicate

> - **Description:** The mean insert size of short paired-end sequencing [high quality](#high-quality-reads), [non duplicated](#duplicated-reads) reads, [primary alignments](#primary-alignments), mapped on [GRCh38 assembly](#grch38-assembly). No minimum [mapping quality](#mapping-quality) is imposed. It is critical that the (BAM/CRAM) alignment files be readily marked for [duplicated reads](#duplicated-reads)
> - **Implementation details:** In the NPM-sample-QC reference implementation it is computed using [GATK Picard’s CollectInsertSizeMetrics](#picard-collectinsertsizemetrics), reporting the MEAN_INSERT_SIZE field. Only the non duplicated reads mapped on GRCh38 assembly are considered. No mapping qualiy is applied.
